# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 355468ce001a2936d4b481da3f1cd7817f3747eed3cc68de77f978cc22c1110abafb02549b0503d8b0e6905d285691c94692e30484e1308ae04fbc526730ce7b

test:
  secret_key_base: 8e016f3d674c630c9c8178a2ba9ada85c3abd4bbe2c6e39c7117f9be5c99b7ca2d5663336588510066fdee74b33e827e55aa7c6ab292613d3901570b276756d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
